name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        modules: 'qtbase'
        setup-python: false
        cache: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgl1-mesa-dev libglu1-mesa-dev \
          libxkbcommon-x11-dev libxcb-icccm4-dev \
          libxcb-image0-dev libxcb-keysyms1-dev \
          libxcb-randr0-dev libxcb-render-util0-dev \
          libxcb-shape0-dev libxcb-xfixes0-dev \
          libxcb-xinerama0-dev libxcb-xkb-dev \
          libxkbcommon-x11-dev libxkbcommon-dev \
          libwayland-dev libxrandr-dev libxrender-dev \
          libxi-dev libxext-dev libxfixes-dev

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -S .

    - name: Build
      run: cmake --build build --parallel $(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UnvisualKode-linux
        path: build/UnvisualKode

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtbase'
        setup-python: false
        cache: true

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -S .

    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UnvisualKode-windows
        path: build/Release/UnvisualKode.exe
